version: '2'
services:
  server:
    container_name: crhackserver
    restart: always
    image: crhack:serverv0.1
    ports:
      - "5000:5000"
  mysql:
    container_name: crhackdb
    restart: always
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'crhack'
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'crhack'
      MYSQL_PASS: 'crhackpass'
    volumes:
      - mysql-data-crhack:/var/lib/mysql
volumes:
  mysql-data-crhack:
