version: '2'
services:
  server:
    container_name: crhackserver
    restart: always
    image: crhack:serverv0.1
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    volumes:
      - mysql-data-crhack:/var/lib/mysql
    ports:
      - "5000:5000"
volumes:
  mysql-data-crhack:
